### ISSUE TITLE
Create dbt converter for Airbyte Linkedin Ads source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#18] opened 2024-07-02 17:40 UTC
The goal of this task is to ensure the Airbyte Linkedin Ads connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/linkedin/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector

**Comment by ombhardwajj** [comment] 2024-08-08 14:07
@marcosmarxm Please assign it to me!

**Comment by ombhardwajj** [comment] 2024-08-08 16:18
I am done with step 1 , can you please confirm if I have correctly done this? 
If yes can I proceed to step 2?
@marcosmarxm 

### Common and Unique Streams in Fivetran and Airbyte LinkedIn Ads Connectors

| **Fivetran**                     | **Airbyte**       
|-----------------------------------------|---------------------------|
| `linkedin_ads__account_report`          | ❌ it doesn't exist             
| `linkedin_ads__campaign_group_report`   | `CampaignGroups`          
| `linkedin_ads__campaign_report`         | `Campaigns`              
| `linkedin_ads__creative_report`         | `Creatives`               
| `linkedin_ads__url_report`              | ❌ it doesn't exist         
| `linkedin_ads__conversions`             | `Conversions`

**Comment by marcosmarxm** [comment] 2024-08-08 17:14
The models you need to analyse (sqls) are from here: https://github.com/fivetran/dbt_linkedin_source/tree/main/models

**Comment by ombhardwajj** [comment] 2024-08-08 18:07
Sorry for the oversight last time 🙇 

| **Fivetran Stream**           | **Airbyte Stream**                       |
|-------------------------------|------------------------------------------|
| ad_analytics_by_creative       | ❌ it doesn't exist |
| creative_history               | Creatives                                |
| campaign_history               | Campaigns                                |
| campaign_group_history         | CampaignGroups                           |
| account_history                | Accounts                                 |
| ad_analytics_by_campaign       | ❌ it doesn't exist |

Please check and confirm this @marcosmarxm

**Comment by marcosmarxm** [comment] 2024-08-08 18:24
Airbyte called these `ad_campaign_analytics` and `ad_created_analytics`!

**Comment by marcosmarxm** [comment] 2024-08-08 19:56
Approved for step 2!

**Comment by ombhardwajj** [comment] 2024-08-09 16:51
Hey @marcosmarxm I've been working on step 2 and  
I wanted to confirm if it's possible that one SQL table in the Fivetran dbt can have multiple related tables in the Airbyte dbt, like in Table 2!

Links : [Fivetran dbt](https://github.com/fivetran/dbt_linkedin_source/tree/main/models) [Airbyte dbt](https://github.com/airbytehq/airbyte-dbt-models/tree/main/connectors/source_linkedin_ads/models/source)

### Table 1) 
**stg_linkedin_ads__account_history.sql**
- In Airbyte: `accounts.yaml`

| **Fivetran Column**                             | **Airbyte Column**            |
|-------------------------------------------------|-------------------------------|
| **id (account_id)**                             | **id**                        |
| **name (account_name)**                         | **name**                      |
| **currency**                                    | **currency**                  |
| **version_tag**                                 | **version** (object)          |
| **status**                                      | **status**                    |
| **type**                                        | **type**                      |
| **last_modified_time (last_modified_at)**       | **lastModified**              |
| **created_time (created_at)**                   | **created**                   |
| **source_relation**                             | ❌ Not present                |
| **is_latest_version**                           | ❌ Not present                |
| **test**                                        | **test**                      |
| **notifiedOnCreativeRejection**                 | ❌ Not present                |
| **notifiedOnNewFeaturesEnabled**                | ❌ Not present                |
| **notifiedOnEndOfCampaign**                     | ❌ Not present                |
| **servingStatuses**                             | ❌ Not present                |
| **notifiedOnCampaignOptimization**              | ❌ Not present                |
| **reference**                                   | ❌ Not present                |
| **notifiedOnCreativeApproval**                  | ❌ Not present                |


### Table 2) 
**stg_linkedin_ads__ad_analytics_by_campaign.sql** 
- In Airbyte: `ad_campaign_analytics.yaml` and possibly another table `campaigns.yaml`.

| **Fivetran**                       | **Airbyte**                                            |
|------------------------------------|--------------------------------------------------------|
| **campaign_id**                    | **id** (from `campaigns.yaml`)                         |
| **clicks**                         | **clicks**                                             |
| **impressions**                    | **impressions**                                        |
| **costInLocalCurrency**            | **costInLocalCurrency**                                |
| **costInUsd**                      | **costInUsd**                                          |
| **conversion_value_in_local_currency** | **conversionValueInLocalCurrency**                |
| **date_day**                       | Can be derived from **start_date** and **end_date** in Airbyte |
| **source_relation**                | ❌ Not present                                         |

### Table 3) 
**stg_linkedin_ads__ad_analytics_by_creative.sql**
- In Airbyte: `ad_creative_analytics.yaml`.

| **Fivetran**                       | **Airbyte**                                            |
|------------------------------------|--------------------------------------------------------|
| **clicks**                         | **clicks**                                             |
| **impressions**                    | **impressions**                                        |
| **cost_in_local_currency**         | **costInLocalCurrency**                                |
| **cost_in_usd**                    | **costInUsd**                                          |
| **conversion_value_in_local_currency** | **conversionValueInLocalCurrency**                |
| **date_day**                       | Can be derived from **start_date** and **end_date** in Airbyte |
| **source_relation**                | ❌ Not present                                         |
| **creative_id**                    | ❌ Not present                                         |

### Table 4) 
**stg_linkedin_ads__campaign_group_history.sql**
- In Airbyte: `campaign_groups.yaml`.

| **Fivetran**                       | **Airbyte**                                            |
|------------------------------------|--------------------------------------------------------|
| **campaign_group_id**              | **id**                                                 |
| **name**                           | **name**                                               |
| **account_id**                     | **account** (Not sure if they are the same)            |
| **status**                         | **status**                                             |
| **is_backfilled**                  | **backfilled**                                         |
| **run_schedule_start**             | **runSchedule** (it's an object)                       |
| **run_schedule_end**               | **runSchedule** (it's an object)                       |
| **last_modified_at**               | **lastModified**                                       |
| **created_at** (time only)         | **created** (returns date and time)                    |
| **source_relation**                | ❌ Not present                                         |
| **is_latest_version**              | ❌ Not present                                         |

### Table 5) 
**stg_linkedin_ads__campaign_history.sql**
- In Airbyte: `campaigns.yaml`.

| **Fivetran**                       | **Airbyte**                                            |
|------------------------------------|--------------------------------------------------------|
| **campaign_id**                    | **id**                                                 |
| **campaign_name**                  | **name**                                               |
| **type**                           | **type**                                               |
| **campaign_group_id**              | **campaignGroup**                                      |
| **account_id**                     | **account**                                            |
| **status**                         | **status**                                             |
| **daily_budget_amount**            | **dailyBudget**                                        |
| **unit_cost_amount**               | **unitCost**                                           |
| **creative_selection**             | **creativeSelection**                                  |
| **cost_type**                      | **costType**                                           |
| **format**                         | **format**                                             |
| **objective_type**                 | **objectiveType**                                      |
| **optimization_target_type**       | **optimizationTargetType**                             |
| **audience_expansion_enabled**     | **audienceExpansionEnabled**                           |
| **offsite_delivery_enabled**       | **offsiteDeliveryEnabled**                             |
| **run_schedule_start**             | **runSchedule**                                        |
| **run_schedule_end_at**            | **runSchedule**                                        |
| **last_modified_time**             | **lastModified**                                       |
| **created_time** (time only)       | **created** (date and time String)                     |
| **source_relation**                | ❌ Not present                                         |
| **version_tag**                    | **version** (object)                                   |
| **daily_budget_currency_code**     | ❌ Not present                                         |
| **unit_cost_currency_code**        | ❌ Not present                                         |
| **locale_country**                 | **locale** (object)                                    |
| **locale_language**                | **locale** (object)                                    |
| **is_latest_version**              | ❌ Not present                                         |

### Table 6) 
**stg_linkedin_ads__creative_history.sql**
- In Airbyte: `creatives.yaml`.

| **Fivetran Column**                             | **Airbyte Column**            |
|-------------------------------------------------|-------------------------------|
| **id (creative_id)**                            | **id**                        |
| **campaign_id**                                 | **campaign** (not sure)       |
| **status (coalesce status, intended_status)**   | **intendedStatus**            |
| **click_uri**                                   | ❌ Not present                |
| **last_modified_at**                            | **lastModifiedAt**            |
| **created_at**                                  | **createdAt**                 |
| **source_relation**                             | ❌ Not present                |
| **is_latest_version**                           | ❌ Not present                |
| **base_url**                                    | ❌ Not present                |
| **url_host**                                    | ❌ Not present                |
| **url_path**                                    | ❌ Not present                |
| **utm_source**                                  | ❌ Not present                |
| **utm_medium**                                  | ❌ Not present                |
| **utm_campaign**                                | ❌ Not present                |
| **utm_content**                                 | ❌ Not present                |
| **utm_term**                                    | ❌ Not present                |

**Comment by ombhardwajj** [comment] 2024-08-10 18:09
Hey @marcosmarxm 

I am planning to start with table 2 
But before I begin I need your some clarification from you
1)What do I do with source_relation since its not present.

2)it's possible that one SQL table in the Fivetran dbt can have multiple related tables in the Airbyte dbt..Right?
  Like in Table 2 all except one field(id belongs to campaigns.yaml) belong to ad_campaign_analytics.yaml

**Comment by marcosmarxm** [comment] 2024-08-10 18:18
1. Just ignore, Fivetran you can combine different connectors. It won't be necessary for now. It will be empty.
2. Yes

**Comment by ombhardwajj** [comment] 2024-08-10 19:59
Hey @marcosmarxm 
I've made a PR , added a commit can you confirm if I am on the right path?
I have not yet run `dbt run`
Can you explain me what to do with profiles.yml ,will you give some sample data for testing purposes?

**Comment by ombhardwajj** [comment] 2024-08-14 16:15
Hey @marcosmarxm 

I am getting this error on executing `dbt run`
Can you please help me with this?

 I dont really understand what's causing this....

Line 19 is `select * from tmp` in
connectors/source_linkedin_ads/models/fivetran_converter/stg_linkedin_ads__ad_analytics_by_campaign.sql 

<img width="1102" alt="Screenshot 2024-08-14 at 9 40 24 PM" src="https://github.com/user-attachments/assets/e523304f-96c4-4b97-bcd9-dbaa86d93f14">

**Comment by ombhardwajj** [comment] 2024-08-14 18:32
Update : I've fixed that error!!

**Comment by ombhardwajj** [comment] 2024-08-14 19:17
Hey @marcosmarxm

I am getting this error on executing dbt run
Can you please help me with this?

<img width="1174" alt="Screenshot 2024-08-15 at 12 47 10 AM" src="https://github.com/user-attachments/assets/b3ac9f9f-da17-4421-aae1-5c5c347684ba">

**Comment by marcosmarxm** [comment] 2024-08-14 20:15
Send command in Slack. Let me know if that worked.

**Comment by ombhardwajj** [comment] 2024-08-15 06:56
Thanks @marcosmarxm 
Table 2 transformation has been succesfully completed :) !!

**Comment by ombhardwajj** [comment] 2024-08-15 09:46
Hey @marcosmarxm 
The type column is defined in campaigns.yaml but is not present in the actual campaigns table in the database. 
This discrepancy is causing the dbt run command to fail for Table 5.
Please check

**Comment by ombhardwajj** [comment] 2024-08-15 09:58
@marcosmarxm 
Only the transformations for Table 1 and 6 are left after this.
Can you confirm if I can proceed ahead ignoring the missing columns like you can see below:

### Table 1) 
**stg_linkedin_ads__account_history.sql**
- In Airbyte: `accounts.yaml`

| **Fivetran Column**                             | **Airbyte Column**            |
|-------------------------------------------------|-------------------------------|
| **id (account_id)**                             | **id**                        |
| **name (account_name)**                         | **name**                      |
| **currency**                                    | **currency**                  |
| **version_tag**                                 | **version** (object)          |
| **status**                                      | **status**                    |
| **type**                                        | **type**                      |
| **last_modified_time (last_modified_at)**       | **lastModified**              |
| **created_time (created_at)**                   | **created**                   |
| **source_relation**                             | ❌ Not present                |
| **is_latest_version**                           | ❌ Not present                |
| **test**                                        | **test**                      |
| **notifiedOnCreativeRejection**                 | ❌ Not present                |
| **notifiedOnNewFeaturesEnabled**                | ❌ Not present                |
| **notifiedOnEndOfCampaign**                     | ❌ Not present                |
| **servingStatuses**                             | ❌ Not present                |
| **notifiedOnCampaignOptimization**              | ❌ Not present                |
| **reference**                                   | ❌ Not present                |
| **notifiedOnCreativeApproval**                  | ❌ Not present                |


### Table 6) 
**stg_linkedin_ads__creative_history.sql**
- In Airbyte: `creatives.yaml`.

| **Fivetran Column**                             | **Airbyte Column**            |
|-------------------------------------------------|-------------------------------|
| **id (creative_id)**                            | **id**                        |
| **campaign_id**                                 | **campaign** (not sure)       |
| **status (coalesce status, intended_status)**   | **intendedStatus**            |
| **click_uri**                                   | ❌ Not present                |
| **last_modified_at**                            | **lastModifiedAt**            |
| **created_at**                                  | **createdAt**                 |
| **source_relation**                             | ❌ Not present                |
| **is_latest_version**                           | ❌ Not present                |
| **base_url**                                    | ❌ Not present                |
| **url_host**                                    | ❌ Not present                |
| **url_path**                                    | ❌ Not present                |
| **utm_source**                                  | ❌ Not present                |
| **utm_medium**                                  | ❌ Not present                |
| **utm_campaign**                                | ❌ Not present                |
| **utm_content**                                 | ❌ Not present                |
| **utm_term**                                    | ❌ Not present                |

**Comment by marcosmarxm** [comment] 2024-08-15 12:04
@ombhardwajj your report is very confusing. What we need is compare Fivetran with Airbyte.
From https://github.com/fivetran/dbt_linkedin_source/blob/main/models/stg_linkedin_ads__account_history.sql
here you can find ALL fields Fivetran is using to run the models.
You must compare only these fields with Airbyte.

`Accounts`
| **Fivetran Column**                             | **Airbyte Column**            |
|-------------------------------------------------|-------------------------------|
| **id (account_id)**                             | **id**                        |
| **name (account_name)**                         | **name**                      |
| **currency**                                    | **currency**                  |
| **version_tag**                                 | **version** (object)          |
| **status**                                      | **status**                    |
| **type**                                        | **type**                      |
| **last_modified_time (last_modified_at)**       | **lastModified**              |
| **created_time (created_at)**                   | **created**                   |

All good.

**Comment by ombhardwajj** [comment] 2024-08-15 12:44
Oh yes @marcosmarxm  you are right , thats a blunder I committed with table 1 .  Sorry for the confusion!!

What about the missing type column in the actual postgres DB for Table 5(type is present in campaigns.yaml but not in DB)?

And table 6 is correct I've confirmed it. Can you please tell what to do about the missing columns?

**Closed** 2024-09-03 16:35 UTC
